version: "3.9"

services:
  gubio:
    # ⚠ Cambia <OWNER> por el usuario de GitHub de la chica, igual que en la imagen del pipeline
    image: ghcr.io/gubiogubio/nala-app:1.0.5
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # HTTP
        - "traefik.http.routers.gubio.entrypoints=http"
        - "traefik.http.routers.gubio.rule=Host(`gubio.byronrm.com`)"

        # Redirección a HTTPS
        - "traefik.http.middlewares.gubio-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.gubio.middlewares=gubio-https-redirect"

        # HTTPS
        - "traefik.http.routers.gubiotags.entrypoints=https"
        - "traefik.http.routers.gubiotags.rule=Host(`nala.byronrm.com`)"
        - "traefik.http.routers.gubiotags.tls=true"
        - "traefik.http.routers.gubiotags.tls.certresolver=http"

        # Puerto interno de Flask
        - "traefik.http.services.gubio.loadbalancer.server.port=2407"
        - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
